#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : One-offs  # The title of the book. Will be placed in the left navbar.
author                      : Benjamin D. Pedigo  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        :   # A path to the book logo

# Linking
html:
  favicon: 
  comments:
    hypothesis: true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  home_page_in_navbar: true
  

# Information about where the book exists on the web
repository:
  url: https://github.com/neurodata/bilateral-connectome
  path_to_book: one-offs
  branch: main

sphinx:
  config:
    language: en

latex:
  latex_documents:
    targetname: bilateral-connectome.tex
    theme: howto
  latex_elements: "test" # does not seem to be working

execute: 
  execute_notebooks: off # TODO turn back on someday

bibtex_bibfiles:
  - references.bib
  # - jovo_all_bib.bib

parse:
  myst_enable_extensions: #https://myst-parser.readthedocs.io/en/latest/sphinx/reference.html#sphinx-config-options
    - linkify # automatically identify “bare” web URLs and add hyperlinks
    - dollarmath
  myst_nb_output_stderr: 
    - 'remove'